export const currentUser = {
  id: 'user-001',
  name: 'Hermione Granger',
  email: 'hermione@hogwarts.com',
  avatar: '👩‍🎓',
  bio: 'Passionate learner and mentor. Expert in various magical arts.',
  credits: 450,
  level: 'Emerald Gardener',
  joinDate: '2024-01-15',
  teachingSkills: [
    { id: 1, name: 'Potion Brewing', level: 'Expert', sessions: 25 },
    { id: 2, name: 'Herbology', level: 'Advanced', sessions: 18 },
  ],
  learningSkills: [
    { id: 3, name: 'Divination', level: 'Beginner', sessions: 5 },
    { id: 4, name: 'Transfiguration', level: 'Intermediate', sessions: 12 },
  ],
  achievements: [1, 2, 4],
  completedSessions: 45,
  rating: 4.8,
  reviews: 23,
}

export const mentors = [
  {
    id: 'mentor-001',
    name: 'Severus Snape',
    avatar: '👨‍🏫',
    speciality: 'Potion Brewing',
    rating: 4.9,
    reviews: 156,
    credits: 2500,
    bio: 'Master of potions with years of experience.',
    experience: '15 years',
    responseTime: '< 1 hour',
    availability: 'Weekdays 5-8 PM',
    hourlyRate: 50,
    students: 234,
  },
  {
    id: 'mentor-002',
    name: 'Minerva McGonagall',
    avatar: '👩‍🏫',
    speciality: 'Transfiguration',
    rating: 4.95,
    reviews: 189,
    credits: 3200,
    bio: 'Expert in transformation and magical arts.',
    experience: '20 years',
    responseTime: '< 30 min',
    availability: 'Daily 2-6 PM',
    hourlyRate: 60,
    students: 312,
  },
  {
    id: 'mentor-003',
    name: 'Albus Dumbledore',
    avatar: '👴',
    speciality: 'Advanced Magic',
    rating: 5.0,
    reviews: 245,
    credits: 5000,
    bio: 'Legendary wizard sharing ancient knowledge.',
    experience: '50 years',
    responseTime: '< 2 hours',
    availability: 'Weekends 10 AM-4 PM',
    hourlyRate: 100,
    students: 500,
  },
  {
    id: 'mentor-004',
    name: 'Filius Flitwick',
    avatar: '🧙‍♂️',
    speciality: 'Charm Work',
    rating: 4.87,
    reviews: 142,
    credits: 1800,
    bio: 'Specialist in charm magic and enchantments.',
    experience: '25 years',
    responseTime: '< 1.5 hours',
    availability: 'Mon, Wed, Fri 6-9 PM',
    hourlyRate: 45,
    students: 178,
  },
]

export const skills = [
  {
    id: 1,
    name: 'Herbology Basics',
    category: 'Nature',
    icon: '🌿',
    difficulty: 'Beginner',
    demand: 'High',
    mentorCount: 12,
    rating: 4.7,
  },
  {
    id: 2,
    name: 'Advanced Potion Brewing',
    category: 'Magic',
    icon: '🧪',
    difficulty: 'Advanced',
    demand: 'Medium',
    mentorCount: 8,
    rating: 4.9,
  },
  {
    id: 3,
    name: 'Defensive Spellcasting',
    category: 'Combat',
    icon: '🛡️',
    difficulty: 'Intermediate',
    demand: 'Very High',
    mentorCount: 15,
    rating: 4.8,
  },
  {
    id: 4,
    name: 'Wand Craftsmanship',
    category: 'Crafts',
    icon: '🪄',
    difficulty: 'Expert',
    demand: 'Low',
    mentorCount: 3,
    rating: 5.0,
  },
  {
    id: 5,
    name: 'Divination Mastery',
    category: 'Magic',
    icon: '🔮',
    difficulty: 'Intermediate',
    demand: 'Medium',
    mentorCount: 6,
    rating: 4.5,
  },
]

export const sessions = [
  {
    id: 'session-001',
    mentorId: 'mentor-001',
    mentorName: 'Severus Snape',
    mentorAvatar: '👨‍🏫',
    skillName: 'Potion Brewing',
    date: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
    time: '6:00 PM - 7:00 PM',
    status: 'confirmed',
    credits: 50,
    duration: 60,
    description: 'Learn advanced potion brewing techniques',
    meetingLink: 'https://herbology-hub.com/meeting/session-001',
  },
  {
    id: 'session-002',
    mentorId: 'mentor-002',
    mentorName: 'Minerva McGonagall',
    mentorAvatar: '👩‍🏫',
    skillName: 'Transfiguration',
    date: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000),
    time: '3:00 PM - 4:00 PM',
    status: 'pending',
    credits: 30,
    duration: 60,
    description: 'Master basic transformation spells',
    meetingLink: null,
  },
]

export const leaderboard = [
  { rank: 1, name: 'Albus Dumbledore', avatar: '👴', credits: 5000, sessions: 200, level: 'Grand Master' },
  { rank: 2, name: 'Severus Snape', avatar: '👨‍🏫', credits: 2500, sessions: 120, level: 'Master' },
  { rank: 3, name: 'Minerva McGonagall', avatar: '👩‍🏫', credits: 3200, sessions: 150, level: 'Master' },
  { rank: 4, name: 'Filius Flitwick', avatar: '🧙‍♂️', credits: 1800, sessions: 95, level: 'Senior Mentor' },
  { rank: 5, name: 'Rubeus Hagrid', avatar: '🧔', credits: 1200, sessions: 70, level: 'Mentor' },
  { rank: 6, name: 'Remus Lupin', avatar: '👨', credits: 980, sessions: 60, level: 'Mentor' },
  { rank: 7, name: 'Horace Slughorn', avatar: '👴', credits: 850, sessions: 45, level: 'Instructor' },
  { rank: 8, name: 'Aurora Sinistra', avatar: '👩', credits: 720, sessions: 38, level: 'Instructor' },
  { rank: 9, name: 'Hermione Granger', avatar: '👩‍🎓', credits: 450, sessions: 25, level: 'Gardener' },
  { rank: 10, name: 'Harry Potter', avatar: '👦', credits: 380, sessions: 20, level: 'Gardener' },
]

export const recommendations = [
  {
    id: 1,
    mentorId: 'mentor-001',
    mentorName: 'Severus Snape',
    mentorAvatar: '👨‍🏫',
    skill: 'Potion Brewing',
    compatibility: 92,
    reason: 'Matches your learning style perfectly',
    availability: 'Available Today',
  },
  {
    id: 2,
    mentorId: 'mentor-003',
    mentorName: 'Albus Dumbledore',
    mentorAvatar: '👴',
    skill: 'Advanced Magic Theory',
    compatibility: 88,
    reason: 'Expert in topics you\'re interested in',
    availability: 'Next Weekend',
  },
  {
    id: 3,
    mentorId: 'mentor-002',
    mentorName: 'Minerva McGonagall',
    mentorAvatar: '👩‍🏫',
    skill: 'Transfiguration',
    compatibility: 85,
    reason: 'Perfect for intermediate learners',
    availability: 'Tomorrow 2 PM',
  },
]

export const notifications = [
  {
    id: 1,
    type: 'session-confirmed',
    title: 'Session Confirmed',
    message: 'Your session with Severus Snape is confirmed for tomorrow at 6 PM',
    timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    read: false,
  },
  {
    id: 2,
    type: 'credits-earned',
    title: 'Credits Earned',
    message: 'You earned 50 credits from your teaching session',
    timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    read: true,
  },
  {
    id: 3,
    type: 'achievement-unlocked',
    title: 'Achievement Unlocked',
    message: 'You unlocked the "Green Thumb" achievement',
    timestamp: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000),
    read: true,
  },
]

export const TESTIMONIALS = [
  {
    id: 1,
    rating: 5,
    text: 'Herbology Hub helped me master potion brewing in just weeks. The community mentors are amazingly knowledgeable and supportive!',
    image: '👩‍🌾',
    name: 'Luna Lovegood',
    role: 'Magical Botanist',
  },
  {
    id: 2,
    rating: 5,
    text: 'Trading knowledge using credits is brilliant. I taught herbology basics and earned enough to learn advanced spellcrafting.',
    image: '🧙‍♂️',
    name: 'Neville Longbottom',
    role: 'Herbology Enthusiast',
  },
  {
    id: 3,
    rating: 5,
    text: 'The 1-on-1 sessions were transformative. I went from a beginner to confident spellcaster thanks to the personalized guidance.',
    image: '🧙‍♀️',
    name: 'Ginny Weasley',
    role: 'Spellcraft Practitioner',
  },
]

export const ACHIEVEMENTS = [
  { id: 1, icon: '🌿', name: 'Green Thumb' },
  { id: 2, icon: '🧪', name: 'Potion Prodigy' },
  { id: 3, icon: '🔮', name: 'Future Seer' },
  { id: 4, icon: '🛡️', name: 'Shield Master' },
]


